name: web-server
services:
    postgres:
        container_name: web-server-postgres
        image: postgres:12.19-alpine
        environment:
            PGUSER: wagfm
            POSTGRES_USER: wagfm
            POSTGRES_PASSWORD_FILE: /run/secrets/db_password
            POSTGRES_DB: database
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U wagfm -d database" ]
            interval: 5s
            timeout: 5s
            retries: 20
            start_period: 10s
        volumes:
            - ./src/postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
            - ./postgres_data:/var/lib/postgresql/data
        network_mode: host
        deploy:
            resources:
                limits:
                    cpus: 0.35
                    memory: 0.40G
        secrets:
            - db_password

    nginx:
        container_name: web-server-nginx
        image: nginx:1.27-alpine
        volumes:
            - ./src/nginx.conf:/etc/nginx/nginx.conf
            - ./certs/cert.pem:/etc/nginx/ssl/cert.pem
            - ./certs/key.pem:/etc/nginx/ssl/key.pem
        network_mode: host
        deploy:
            resources:
                limits:
                    cpus: 0.125
                    memory: 0.25G
secrets:
    db_password:
        file: ./db_password.txt